
bin:= ./bin


all: ejprop4 sumador consumidorf productorf tarea6 tarea7 tarea8

ejprop4: ejprop4.c
	gcc $< -o $(bin)/$@
consumidorf: consumidorf.c
	gcc $< -o $(bin)/$@
productorf: productorf.c
	gcc $< -o $(bin)/$@
tarea6: tarea6.c
	gcc $< -o $(bin)/$@
tarea7: tarea7.c
	gcc $< -o $(bin)/$@
tarea8: tarea8.c
	gcc $< -o $(bin)/$@
sumador: sumador.c
	gcc $< -o $(bin)/$@

clean:
	rm -f $(bin)/*